config/routes.rb
CsvError::Application.routes.draw do |map|
  resources :activities

  resources :users

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  validates_presence_of :what, :message => "&nbsp;-&nbsp;required"
  validates_presence_of :desc, :message => "&nbsp;-&nbsp;required"
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :email, :message => "&nbsp;-&nbsp;required"
  #validates_format_of :email, :with => /^[a-zA-Z0-9_.\-]+@[a-zA-Z0-9\-]+.[a-zA-Z0-9\-.]+$/, :message => "&nbsp;-&nbsp;invalid e-mail format"
  validates_presence_of :password, :on => :create, :message => "&nbsp;-&nbsp;required"
  validates_presence_of :password_confirmation, :on => :create, :message => "&nbsp;-&nbsp;required"
  
  attr_accessor :password_confirmation
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  # GET /activities
  # GET /activities.xml
  def index
    @activities = Activity.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @activities }
    end
  end

  # GET /activities/1
  # GET /activities/1.xml
  def show
    @activity = Activity.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @activity }
    end
  end

  # GET /activities/new
  # GET /activities/new.xml
  def new
    @activity = Activity.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @activity }
    end
  end

  # GET /activities/1/edit
  def edit
    @activity = Activity.find(params[:id])
  end

  # POST /activities
  # POST /activities.xml
  def create
    @activity = Activity.new(params[:activity])

    respond_to do |format|
      if @activity.save
        format.html { redirect_to(@activity, :notice => 'Activity was successfully created.') }
        format.xml  { render :xml => @activity, :status => :created, :location => @activity }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @activity.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /activities/1
  # PUT /activities/1.xml
  def update
    @activity = Activity.find(params[:id])

    respond_to do |format|
      if @activity.update_attributes(params[:activity])
        format.html { redirect_to(@activity, :notice => 'Activity was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @activity.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.xml
  def destroy
    @activity = Activity.find(params[:id])
    @activity.destroy

    respond_to do |format|
      format.html { redirect_to(activities_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  layout 'application'
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.xml
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to(@user, :notice => 'User was successfully created.') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/activities/_form.html.erb
<%= form_for :activity, 
             :html => {:id => "new-activity"},
             :validations => true do |f| %>

  <%= f.label :what %><br/>
  <%= f.text_field :what %><br/>
  <%= f.label :desc %><br/>
  <%= f.text_field :desc %><br/>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= form_for :activity, 
             :html => {:id => "edit-activity"},
             :validations => true do |f| %>

  <%= f.label :what %><br/>
  <%= f.text_field :what %><br/>
  <%= f.label :desc %><br/>
  <%= f.text_field :desc %><br/>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/activities/_form2.html.erb
<%= form_for :activity, 
             :html => {:id => "edit-activity"},
             :validations => true do |f| %>

  <%= f.label :what %><br/>
  <%= f.text_field :what %><br/>
  <%= f.label :desc %><br/>
  <%= f.text_field :desc %><br/>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<h1>Editing activity</h1>

<%= render 'form' %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<h1>Listing activities</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @activities.each do |activity| %>
  <tr>
    <td><%= link_to 'Show', activity %></td>
    <td><%= link_to 'Edit', edit_activity_path(activity) %></td>
    <td><%= link_to 'Destroy', activity, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Activity', new_activity_path %>

app/views/activities/new.html.erb
<h1>New activity</h1>

<%= render 'form' %>

<%= link_to 'Back', activities_path %>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_activity_path(@activity) %> |
<%= link_to 'Back', activities_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CsvError</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag 'jquery-1.3.min', 'jquery.validate', 'client_side_validations' %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for :user, 
             :html => {:id => "login-form"}, 
             :validations => true do |f| %>

  <%= f.label :email %><br/>
  <%= f.text_field :email %><br/>
  <%= f.label :password %><br/>
  <%= f.text_field :password %><br/>
  <%= f.label :password_confirmation %><br/>
  <%= f.text_field :password_confirmation %><br/>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= form_for :user, 
             :html => {:id => "edit-form"}, 
             :validations => true do |f| %>

  <%= f.label :email %><br/>
  <%= f.text_field :email %><br/>
  <%= f.label :password %><br/>
  <%= f.text_field :password %><br/>
  <%= f.label :password_confirmation %><br/>
  <%= f.text_field :password_confirmation %><br/>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_form2.html.erb
<%= form_for :user, 
             :html => {:id => "edit-form"}, 
             :validations => true do |f| %>

  <%= f.label :email %><br/>
  <%= f.text_field :email %><br/>
  <%= f.label :password %><br/>
  <%= f.text_field :password %><br/>
  <%= f.label :password_confirmation %><br/>
  <%= f.text_field :password_confirmation %><br/>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>